# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    #    registries:
    #      - github-fusion
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100

  - package-ecosystem: docker
    directory: "/build/package"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: terraform
    directory: "/deployments/terraform"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

#registries:
#  github-fusion:
#    type: git
#    url: https://github.com
#    username: x-access-token
#    password: ${{secrets.FUSION_GITHUB}}
