apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fusion-ai

resources:
  - ../../base
  - signoz

replicas:
  - name: mcp-server-template-deploy
    count: 1

configMapGenerator:
  - name: mcp-server-template-vars
    namespace: fusion-ai
    behavior: merge
    literals:
      - MCP_SERVER_HOST="mcp-server-template.local"
  - name: mcp-server-template-config
    namespace: fusion-ai
    behavior: merge
    literals:
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-collector.fusion-ai.svc.cluster.local:4317"
      - OTEL_TRACES_SAMPLER_ARG="1.0" # 100%

patches:
  # Remove secrets mounting as not used in local dev
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mcp-server-template-deploy
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/imagePullPolicy"
        value: Never
      - op: replace
        path: "/spec/template/spec/topologySpreadConstraints/0/whenUnsatisfiable"
        value: ScheduleAnyway
      - op: remove
        path: "/spec/template/spec/volumes"
      - op: remove
        path: "/spec/template/spec/containers/0/volumeMounts"
  - target:
      kind: Certificate
      namespace: istio-system
      name: mcp-server-template-cert
    patch: |-
      - op: replace
        path: "/spec/issuerRef/name"
        value: selfsigned-issuer
