apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: fusion-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: signoz/signoz-otel-collector:0.111.27
          args: ["--config=/conf/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /conf
          ports:
            - containerPort: 4317
              name: grpc
            - containerPort: 4318
              name: http
      volumes:
        - name: config
          configMap:
            name: signoz-config-defaults
