apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  managed-by: kustomize
  part-of: fusion

resources:
  - istio
  - resources/namespace.yaml
  - mcp-server

vars:
  - name: MCP_SERVER_HOST
    objref:
      kind: ConfigMap
      name: mcp-server-template-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.MCP_SERVER_HOST

configMapGenerator:
  - name: mcp-server-template-vars
    namespace: fusion-ai
    behavior: create
    literals:
      - MCP_SERVER_HOST=""
